# Generated by Django 5.2.1 on 2025-05-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
